<a href="https://colab.research.google.com/github/akash-dev0/ml-journey/blob/main/PRACTICE_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd

In [17]:
from google.colab import files
uploaded = files.upload()

Saving Coffee Shop Sales.xlsx to Coffee Shop Sales.xlsx

In [21]:
df = pd.read_excel("Coffee Shop Sales.xlsx")

In [22]:
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 12.5+ MB

In [26]:
df['revenue'] = df['unit_price'] * df['transaction_qty']

In [27]:
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,revenue
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.0
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.0
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.0
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
 11  revenue           149116 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(5)
memory usage: 13.7+ MB

In [29]:
df['transaction_time'].dtype

dtype('O')

In [31]:
df['transaction_time'].head()

0    07:06:11
1    07:08:56
2    07:14:04
3    07:20:24
4    07:22:41
Name: transaction_time, dtype: object

In [51]:
df['transaction_time'] = pd.to_datetime(df['transaction_time'])
df['transaction_time'].dtype

TypeError: <class 'datetime.time'> is not convertible to datetime, at position 0

In [52]:
df['transaction_time'].iloc[0]

datetime.time(7, 6, 11)

In [53]:
df['transaction_time'].iloc[0]
type(df['transaction_time'].iloc[0])

datetime.time

In [54]:
df['hour'] = df['transaction_time'].apply(lambda t: t.hour)

In [55]:
df[['transaction_time', 'hour']].head()

  transaction_time  hour
0         07:06:11     7
1         07:08:56     7
2         07:14:04     7
3         07:20:24     7
4         07:22:41     7

In [56]:
hourly_revenue = df.groupby('hour')['revenue'].mean()

In [57]:
hourly_revenue_sorted  = hourly_revenue.sort_values(ascending = True)

In [58]:
hourly_revenue_sorted.head()

hour
16    4.522462
18    4.572713
17    4.589401
12    4.615617
14    4.623837
Name: revenue, dtype: float64

In [59]:
df.groupby('hour')['revenue'].count()

hour
6      4594
7     13428
8     17654
9     17764
10    18545
11     9766
12     8708
13     8714
14     8933
15     8979
16     9093
17     8745
18     7498
19     6092
20      603
Name: revenue, dtype: int64

In [63]:
df.store_location.head()

0    Lower Manhattan
1    Lower Manhattan
2    Lower Manhattan
3    Lower Manhattan
4    Lower Manhattan
Name: store_location, dtype: object

In [64]:
df.store_location.info()

<class 'pandas.core.series.Series'>
RangeIndex: 149116 entries, 0 to 149115
Series name: store_location
Non-Null Count   Dtype
--------------   -----
149116 non-null  object
dtypes: object(1)
memory usage: 1.1+ MB

In [67]:
df.store_location.unique()

array(['Lower Manhattan', "Hell's Kitchen", 'Astoria'], dtype=object)

In [68]:
df.store_location.value_counts()

store_location
Hell's Kitchen     50735
Astoria            50599
Lower Manhattan    47782
Name: count, dtype: int64

In [69]:
total_revenue = df.groupby('store_location')['revenue'].sum()
total_revenue

store_location
Astoria            232243.91
Hell's Kitchen     236511.17
Lower Manhattan    230057.25
Name: revenue, dtype: float64